### ISSUE TITLE
Furuno additions - block_coupon

### ISSUE THREAD

**Issue by frederikmillingpytlick** [praxisdigital/moodle-block_coupon#1]
See: https://github.com/praxisdigital/moodle-opgaver/issues/276

**Comment by frederikmillingpytlick** [comment]
The block_coupon_coursegroupings table is now fixed
![image](https://github.com/praxisdigital/moodle-block_coupon/assets/78727001/b50ae33f-7d6c-4682-a4e0-4c1a140b0b24)

**Comment by superfoght** [comment]
Approved. Waiting a bit to release it :)
