### ISSUE TITLE
Estimate for new feature to limit course selection

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_coupon#3]
When you want to generate a license key for courses, it shows ALL the courses on the moodle platform..

![Image](https://github.com/praxisdigital/moodle-block_coupon/assets/2778015/f4ab526b-fa86-4c95-b25c-205ddc91dc69)

The client has a wish for a feature where they can limit which courses are able to be selected. Can we make a setting where they could select which courses are available for selection through the site admin?

We have made a fork for this block that we could do this in.

What is the estimate for such a feature, if it's even possible?

**Comment by mcardle** [comment]
@superfoght how many course are we talking about - maybe if it is a lot, we could add x categories and all courses in these categories are available or how complex should it be?

**Comment by superfoght** [comment]
@mcardle they want to pick out something like 10-20 courses.

**Comment by mcardle** [comment]
Okay, we will do a course selector, like suggested.

**Comment by mcardle** [comment]
First estimate the task and report back to Bo

**Comment by frederikmillingpytlick** [comment]
@superfoght 

I estimate this to take 4 hours

**Comment by superfoght** [comment]
Thanks. I have sent the estimate to the client. Will follow up during next week.

**Comment by superfoght** [comment]
Client accepted estimate https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2074298356

**Comment by frederikmillingpytlick** [comment]
Ready for testing. I've added a new setting: "courses_to_show_in_findcourses_dropdown"

**Comment by frederikmillingpytlick** [comment]
Time spent: 1 hour

**Comment by superfoght** [comment]
Works for me - I have asked the client to confirm that it works how they intended
